version: '3.9'

services:
  minio:
    image: minio/minio:latest
    container_name: minio
    environment:
      MINIO_ACCESS_KEY: yourAccessKey
      MINIO_SECRET_KEY: yourSecretKey
    volumes:
      - ./minio_data:/data
    command: server /data
    ports:
      - "9000:9000"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 30s

  fastapi_service:
    build: .
    container_name: fastapi_service
    depends_on:
      - minio
    ports:
      - "8000:8000"
    environment:
      MINIO_ENDPOINT: "http://minio:9000"
      MINIO_ACCESS_KEY: "yourAccessKey"
      MINIO_SECRET_KEY: "yourSecretKey"