FROM python:3.10-slim-bullseye

WORKDIR /

EXPOSE 8000

COPY requirements.txt .

RUN pip install --upgrade --no-cache-dir pip setuptools wheel

# RUN pip install --no-cache-dir -r requirements.txt

COPY . .

RUN dvc init

CMD ["uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]